name: Update Image

on:
  push:
    branches:
      - main  # 僅在 main 分支觸發
  workflow_dispatch:  # 手動觸發
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build judge images
      run: |
        docker build --pull --no-cache -f dockerfile.cpp -t tsukisama9292/judge:cpp-rolling .
        docker build --pull --no-cache -f dockerfile.python -t tsukisama9292/judge:python-rolling .
        docker build --pull --no-cache -f dockerfile.java -t tsukisama9292/judge:java-rolling .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push tsukisama9292/judge:cpp-rolling
        docker push tsukisama9292/judge:python-rolling
        docker push tsukisama9292/judge:java-rolling

  # pull-image:
  #   runs-on: self-hosted
  #   needs: build
  #   if: success()
  #   steps:
  #   - name: Pull the Docker image
  #     run: |
  #       docker pull tsukisama9292/judge:cpp-rolling
  #       docker pull tsukisama9292/judge:python-rolling
  #       docker pull tsukisama9292/judge:java-rolling